// import { Poppins } from "next/font/google";
import "./globals.css";

// const poppins = Poppins({
//   subsets: ["latin"],
// });


export const metadata = {
  title: "Portfolio | Ly Chanvicharo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
